services:
  - type: web
    name: flask-todo-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PORT
        value: 5000
